### ISSUE TITLE
Check failed: valid: Input data contains `inf` or `nan`

### ISSUE THREAD

**Issue by MichelMoser** [agnesdeng/mixgb#2]
Hi, 

Thanks for implementing xgb for imputation. I cant wait to see how it performs on our medical datasets. 

When running some initial tests, i fail to execute the imputation due to an error: 

```
all_data1 <- as.data.frame(all_data)
MIXGB <- Mixgb$new(all_data1, pmm.type="auto", pmm.k = 5)
mixgb.data <- MIXGB$impute(m=5)
```
and got error: 
```
Error in xgb.DMatrix(newdata, missing = missing) : 
  [14:31:13] amalgamation/../src/data/data.cc:945: Check failed: valid: Input data contains `inf` or `nan`

```
There is no Inf in the dataset and I guess its obvious that there are NaN in the data, otherwise there is no point in imputing =) 

Could you help me out? 

Thanks, 
Michel

**Comment by agnesdeng** [comment]
Hi Michel,

In R, missing values are represented by NA. Replace NaN with NA in your dataset should solve this.

**Comment by MichelMoser** [comment]
Hi, 

They are indeed coded as NA. I just checked. 

missingness of the data is only in 8 out of 227 columns: 

```
216 BURNS_SECOND_DEGREE                       0     
217 BURNS_THIRD_DEGREE                        0     
218 ZYSTIC_FIBROSIS                           0     
219 ddimer_value_mcg_l_log                    0     
220 ddimer_value_mcg_l                        0.0484
221 leucocytes_G_l                            0.221 
222 thrombocytes_G_l                          0.221 
223 crp_mg_l                                  0.359 
224 inr                                       0.546 
225 ck_U_L                                    9.54  
226 urea_mmol_l                              11.5   
227 asat_U_l                                 24.4 
```

**Comment by agnesdeng** [comment]
Can you give a reproducible example? e.g, a sample of all_data.

**Comment by MichelMoser** [comment]
Hi, here a small subset. 
Should be reproducible with: 
[test_data.csv](https://github.com/agnesdeng/mixgb/files/7048064/test_data.csv)
`
```

test_data <- read_csv("test_data.csv")
MIXGB <- Mixgb.train$new(test_da, pmm.type="auto", pmm.k = 5)
mixgb.data <- MIXGB$impute(m=5)
```
output: 
```
> mixgb.data <- MIXGB$impute(m=5)
Error in xgb.DMatrix(data, label = label, missing = missing) : 
  [17:11:18] amalgamation/../src/data/data.cc:945: Check failed: valid: Input data contains `inf` or `nan`
```

**Comment by agnesdeng** [comment]
Hi Michel,

I think error messages occur because the data you feed in hasn't been cleaned yet. 

First, in the raw dataset, some variables are of "character" type, they need to be converted to "factor" type in R.
You can simply add the argument `stringsAsFactors=TRUE`  when you read the dataset into R.  

```r
test.df<-read.csv("/Users/agnes/Desktop/test_data.csv")
str(test.df)
test.df<-read.csv("/Users/agnes/Desktop/test_data.csv",stringsAsFactors = TRUE)
str(test.df)
````
Next, there is an **Inf** value in the variable **"var_227"** in your dataset. We need to remove that observation. 

```r
summary(test.df)
which(is.infinite(test.df$var_227))
inf.indx<-which(is.infinite(test.df$var_227))
test.df2<-test.df[-inf.indx,]
```

Then we try to feed in this datset in the imputer, but we will get some errors.
```r
MIXGB <- Mixgb$new(test.df2, pmm.type="auto", pmm.k = 5)
mixgb.data <- MIXGB$impute(m=5)
```

This is because some factor variables in your dataset only have one level.  E.g,  all of them are coded as "No" in one variable.
We need to remove those columns. 

```r
idx<-which(sapply(test.df2, nlevels) == 1)
sub.df<-test.df2[, -idx]
```

Now this cleaned dataset should be ready to feed in the imputer.

If you just want to get multiple imputation for this dataset, use **Mixgb$new()** will save you lots of time since you only have a few columns with missing values. If there are only 8 columns with missing values, it loops 8 times. 

```r
MIXGB <- Mixgb$new(sub.df, pmm.type="auto", pmm.k = 5)
mixgb.data <- MIXGB$impute(m=5)
```

If you use **Mixgb.train$new()**,  you will not only get multiple imputed datasets, but also an ensemble of saved models for imputing new data.

The number of loops depends on the number of columns in you dataset. If there are 200 columns, even only 8 of them have missing values, it will loop 200 times. This is because we need to save an imputation model for each column for later use. As the new data may have missing values in some columns but these columns are fully observed in the training data. 

```r
MIXGB <- Mixgb.train$new(sub.df, pmm.type="auto", pmm.k = 5)
mixgb.obj <- MIXGB$impute(m=5)

newdata.impute=impute.new(object = mixgb.obj, newdata = newdata.df)
newdata.impute
```

**Comment by MichelMoser** [comment]
Hi, 
Thank you very much and sorry for me not spotting those obvious flaws in my dataset. 
Works like a charm now.

**Comment by agnesdeng** [comment]
You are welcome Michel. Let me know if there is any error when you use this package. It's still under development and there are more to fix or add. 

Also, there may be some errors when you use the function **impute.new()** at the moment. For example, if you try to impute a single entry of new data. I am fixing this now and will update the package hopefully by tomorrow. 

Feel free to reinstall the package and run it again if you experience some errors regarding this function next time.

**Comment by MichelMoser** [comment]
just for my understanding: 
As you mentioned the loops per column, i see that removing columns with no missings would improve the speed of the imputation. 
But would i end up with a bad imputer, because it is not trained on all of the available features?

**Comment by agnesdeng** [comment]
In general, you shouldn't remove any column in your dataset when you feed in the imputer, unless under the following conditions:
(a) the column has 100% missing values, there is no point to include this in the imputer;
(b) the column is of the type factor/multiclass, but only presents single level. (It should be removed because it adds nothing useful to the imputation model.)

Other than that, we should always include other variables (even though there is no missing value in it). 

As I mentioned earlier, you can speed up the process by using **Midae$new()** instead of **Midae.train$new()** if you don't need to save the imputer for imputing new unseen data in the future.
